const express=require("express");
const router=express.Router();
const middleware=require("../middleware/authMiddleware");
const {adminMiddleware}=require("../middleware/adminMiddleware");
const upload=require("../middleware/upload");
const {getAllProducts,getProducts,getProductsById,addProduct,updateProduct,removeProduct,productWithCategory,searchProducts,uploadImage,getRelatedProducts,recentlyViewedProducts,searchHistory,deleteHistory}=require("../controllers/productControllers");
router.get("/allproducts",middleware,getAllProducts);
router.get("/admin/allproducts",middleware,adminMiddleware,getAllProducts);
router.get("/products",middleware,getProducts);
router.get("/productswithcategory",middleware,productWithCategory);
router.post("/products",middleware,adminMiddleware,addProduct);
router.put("/:id",middleware,adminMiddleware,updateProduct);
router.delete("/products/:id",middleware,adminMiddleware,removeProduct);
router.get("/search",middleware,searchProducts);
router.get("/viewproduct/:productID",middleware,getProductsById);
router.post("/uploadimage",upload.single("image"),uploadImage);
router.get("/related/:productID",middleware,getRelatedProducts);
router.get("/recentlyViewed",middleware,recentlyViewedProducts);
router.get("/viewhistory",middleware,searchHistory);
router.delete("/deletehistory/:id",middleware,deleteHistory);
module.exports=router;